config/routes.rb
Rails.application.routes.draw do
  resources :students
  # # root "users#index"
  # get "/users", to: "users#index"
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/call.rb
class Call
    def self.after_find(student)
       puts "You find an object through class"
      end
    
  end

app/models/student.rb
class Student < ApplicationRecord



  validates :name, presence: true

  validates :email, presence: true


  before_validation :ensure_login_has_a_value
  private
    def ensure_login_has_a_value
      if name.nil?
        puts "you must enter the name"
      end
     
      if email.nil?
        puts "you must enter the Email address"
      end
    end


    before_create do
      puts "before cerating a object it will call this function "
    end


    after_validation :set_status

    private
      def set_status 
        puts "this funciton is called after the validation"
      end


      after_initialize do |student|
        puts "You have initialized an object!"
      end
    
      after_find do |student|
        puts "You have found an object!"
      end


      after_touch do |student|
        puts "You have touched an object"
      end


      after_save do |student|
        puts "print After Save an object"
      end

      before_update do |student|
        puts "print Before Update an object"
      end

      after_update do |student|
        puts "print After Update an object"
      end

      before_destroy do |student|
        puts "print Before Destroy an object"
       end

      after_destroy do |student|
        puts "print After Destroy an object"
      end


      after_find Call
       
end

app/models/user.rb
class ValidatorClass < ActiveModel::Validator
  def validate(record)
      if record.phone_num == 0000000000
          record.errors.add :phone_num, "you can't use this number"
      end
  end
end


class User < ApplicationRecord
  has_secure_password
  


  validates :name, presence: true
 
  

  validates :name, exclusion: { in: %w(akash yash),
    message: "%{value} is not available." }

    validates :name, format: { with: /\A[a-zA-Z]+\z/,
      message: ": you can't enter number" }

      validates :name, inclusion: { in: %w(small medium large),
        message: "%{value} is not a valid size" }

        validates :name, length: { minimum: 5,
          message:":name should be atleat 5 letter"}

  validates :email, confirmation: {case_sensitive: false}

  validates :phone_num, comparison: { greater_than: :pincode }


  validates :password, numericality: true

  validates :password, numericality: { only_integer: true }

  validates :name, uniqueness: true
  validates :name, uniqueness: {message: "name is already taken"}



  validates :name,  absence: {message: "name must be empty"} #check if filed is empty or not
    
  validates_each :name, :city do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end


  
  
  #if the value is blank it will allows it but the value less then the 5 letter won't be allow
  validates :city, length: { is: 5 }, allow_blank: true

  validates :city, length: { is: 5 }, allow_nil: true


  validates :name,
    uniqueness: {
      message: ->(object, data) do
        " #{data[:value]} is already taken. Try another name"
      end
    }

    validates :password, numericality: { message: "%{value} seems wrong" }
    
    validates :password, numericality: { greater_than: 10 }
    
    validates :password, numericality: { greater_than_or_equal_to:  10 }
    
    validates :name, presence: { strict: true }


    validates_with ValidatorClass

  # before validation choose funciton will be called and if the name length will be less then 5 then and only then it will check validation
    validates :name, uniqueness: true, if: :choose
    def choose
       name.length < 5
    end


    with_options if: :check do |admin|
      admin.validates :password, length: { minimum: 10 }
      admin.validates :email, presence: true
    end
    def check
         name.length < 5
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController



  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :email)
    end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
  
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :email_confirmation, :password, :password_confirmation, :phone_num, :state, :city, :pincode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Form</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>


   <p>
    <b>gender</b><br />
    <%= form.radio_button :gender, 'Male' %> Male<br />
    <%= form.radio_button :gender, 'Female' %> Female<br />
  </p>
 
  <div>
    <%= form.submit %>
  </div>

 
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Gender: </strong>
    <%= student.gender %>
  </p>

  
</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :email_confirmation, style: "display: block" %>
    <%= form.text_field :email_confirmation %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :phone_num, style: "display: block" %>
    <%= form.number_field :phone_num %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :city,style: "display: block"  %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :pincode, style: "display: block" %>
    <%= form.number_field :pincode %>
  </div>


   <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>


  <div>
    <%= form.submit %>
  </div>

 
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>
  
  <p>
    <strong>Phone num:</strong>
    <%= user.phone_num %>
  </p>

  <p>
    <strong>State:</strong>
    <%= user.state %>
  </p>

  <p>
    <strong>City:</strong>
    <%= user.city %>
  </p>

  <p>
    <strong>Pincode:</strong>
    <%= user.pincode %>
  </p>


</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>